name: Publish Packages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Generate Nuget Packages
        run: dotnet pack --configuration Release

      - name: Publish Nuget Packages to Nuget.org
        run: dotnet nuget push src/**/bin/Release/*.nupkg -k ${{secrets.NUGET_API_TOKEN}} -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Publish Nuget Packages to Github
        run: |
          dotnet nuget add source --username lfclementino --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/lfclementino/index.json"
          dotnet nuget push src/**/bin/Release/*.nupkg -s "github" --skip-duplicate